[workspace]
members = [
        "async-brigade",
        "async-mem-brigade",
        "one-thread-brigade",
        "async-creation",
        "thread-brigade",
        "thread-creation",
        "utils",
]
